FROM node:20.12.0-alpine3.19

# 1️⃣ Set working directory
WORKDIR /usr/src/app

# 2️⃣ Install pnpm globally
RUN npm install -g pnpm

# 3️⃣ Copy files
COPY package.json turbo.json tsconfig.json ./
COPY apps ./apps
COPY packages ./packages

# 4️⃣ Install dependencies
RUN pnpm install

# 5️⃣ Build project
RUN pnpm run db:generate && \
    npx turbo build

# 6️⃣ Start app
CMD ["pnpm", "run", "start-user-app"]
