FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY package.json turbo.json tsconfig.json ./
COPY apps ./apps
COPY packages ./packages

RUN pnpm install
RUN npm run db:generate
# Instead of: RUN npm run build
RUN npx turbo build --filter=excelidraw-frontend

CMD ["npm", "run", "start-user-app"]
